version: "3.9"
services:
  boxbilling:
    volumes:
      - .:/var/www/html
    container_name: "boxbilling"
    build: 
      context: .
      dockerfile: bb-dockerfile
    ports:
      - "80:8004"
    depends_on:
      - mysql_db
    networks:
      - dev_network

  mysql_db:
    container_name: "mysql"
    image: mysql:8.0.25
    volumes:
      - ./bb-seeder:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    expose:
      - "3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: boxbilling
      MYSQL_USER: boxbilling
      MYSQL_PASSWORD: boxbilling
      
    networks:
      - dev_network

networks:
  dev_network:
    name: "development"
    driver: bridge
